export enum EMembershipType {
    CHILD = 'CHILD',
    SPOUSE = 'SPOUSE',
    HEAD = 'HEAD',
    ADOPTED_CHILD = 'ADOPTED_CHILD',
    PARENT = 'PARENT',
    SIBLING = 'SIBLING',
    GRAND_CHILD = 'GRAND_CHILD',
    PARENT_IN_LAW = 'PARENT_IN_LAW',
    SIBLING_IN_LAW = 'SIBLING_IN_LAW',
    OTHER_RELATIVE = 'OTHER_RELATIVE',
    OTHER_NON_RELATIVE = 'OTHER_NON_RELATIVE',
}
