export enum EPermission {
    CREATE_HOUSE_HOLD = 'CREATE_HOUSE_HOLD',
    DELETE_HOUSE_HOLD = 'DELETE_HOUSE_HOLD',
    UPDATE_HOUSE_HOLD = 'UPDATE_HOUSE_HOLD',
    TRANSFER_HOUSE_HOLD = 'TRANSFER_HOUSE_HOLD',
    ENABLE_HOUSE_HOLD = 'ENABLE_HOUSE_HOLD',
    DISABLE_HOUSE_HOLD = 'DISABLE_HOUSE_HOLD',
    VIEW_HOUSE_HOLD = 'VIEW_HOUSE_HOLD',
    DOWNLOAD_HOUSE_HOLD = 'DOWNLOAD_HOUSE_HOLD',
    ARCHIVE_HOUSEHOLD = 'ARCHIVE_HOUSEHOLD',
    CREATE_MEMBER = 'CREATE_MEMBER',
    DELETE_MEMBER = 'DELETE_MEMBER',
    UPDATE_MEMBER = 'UPDATE_MEMBER',
    TRANSFER_MEMBER = 'TRANSFER_MEMBER',
    ENABLE_MEMBER = 'ENABLE_MEMBER',
    DISABLE_MEMBER = 'DISABLE_MEMBER',
    VIEW_MEMBER = 'VIEW_MEMBER',
    DOWNLOAD_MEMBER = 'DOWNLOAD_MEMBER',
    CREATE_QUESTIONNAIRE = 'CREATE_QUESTIONNAIRE',
    DELETE_QUESTIONNAIRE = 'DELETE_QUESTIONNAIRE',
    UPDATE_QUESTIONNAIRE = 'UPDATE_QUESTIONNAIRE',
    TRANSFER_QUESTIONNAIRE = 'TRANSFER_QUESTIONNAIRE',
    ENABLE_QUESTIONNAIRE = 'ENABLE_QUESTIONNAIRE',
    DISABLE_QUESTIONNAIRE = 'DISABLE_QUESTIONNAIRE',
    VIEW_QUESTIONNAIRE = 'VIEW_QUESTIONNAIRE',
    DOWNLOAD_QUESTIONNAIRE = 'DOWNLOAD_QUESTIONNAIRE',
    ARCHIVE_QUESTIONNAIRE = 'ARCHIVE_QUESTIONNAIRE',
    CREATE_SYSTEM_USER = 'CREATE_SYSTEM_USER',
    DELETE_SYSTEM_USER = 'DELETE_SYSTEM_USER',
    UPDATE_SYSTEM_USER = 'UPDATE_SYSTEM_USER',
    TRANSFER_SYSTEM_USER = 'TRANSFER_SYSTEM_USER',
    ENABLE_SYSTEM_USER = 'ENABLE_SYSTEM_USER',
    DISABLE_SYSTEM_USER = 'DISABLE_SYSTEM_USER',
    VIEW_SYSTEM_USER = 'VIEW_SYSTEM_USER',
    DOWNLOAD_SYSTEM_USER = 'DOWNLOAD_SYSTEM_USER',
    CREATE_ADMINISTRATIVE_ENTITY = 'CREATE_ADMINISTRATIVE_ENTITY',
    DELETE_ADMINISTRATIVE_ENTITY = 'DELETE_ADMINISTRATIVE_ENTITY',
    UPDATE_ADMINISTRATIVE_ENTITY = 'UPDATE_ADMINISTRATIVE_ENTITY',
    TRANSFER_ADMINISTRATIVE_ENTITY = 'TRANSFER_ADMINISTRATIVE_ENTITY',
    ENABLE_ADMINISTRATIVE_ENTITY = 'ENABLE_ADMINISTRATIVE_ENTITY',
    DISABLE_ADMINISTRATIVE_ENTITY = 'DISABLE_ADMINISTRATIVE_ENTITY',
    VIEW_ADMINISTRATIVE_ENTITY = 'VIEW_ADMINISTRATIVE_ENTITY',
    DOWNLOAD_ADMINISTRATIVE_ENTITY = 'DOWNLOAD_ADMINISTRATIVE_ENTITY',
    CREATE_TARGETING = 'CREATE_TARGETING',
    VIEW_TARGETING = 'VIEW_TARGETING',
    DOWNLOAD_TARGETING = 'DOWNLOAD_TARGETING',
    UPDATE_APPEAL = 'UPDATE_APPEAL',
    UPDATE_COEFFICIENT = 'UPDATE_COEFFICIENT',
    VIEW_COEFFICIENT = 'VIEW_COEFFICIENT',
    VIEW_CUTOFF = 'VIEW_CUTOFF',
    CREATE_CUTOFF = 'CREATE_CUTOFF',
    UPDATE_CUTOFF = 'UPDATE_CUTOFF',
    VIEW_SCORING = 'VIEW_SCORING',
    VIEW_ANSWERS = 'VIEW_ANSWERS',
    UPDATE_ANSWERS = 'UPDATE_ANSWERS',
    VIEW_APPEAL = 'VIEW_APPEAL',
    UPDATE_INSTITUTION = 'UPDATE_INSTITUTION',
    DELETE_INSTITUTION = 'DELETE_INSTITUTION',
    CREATE_INSTITUTION = 'CREATE_INSTITUTION',
    VIEW_INSTITUTION = 'VIEW_INSTITUTION',
    DISABLE_INSTITUTION = 'DISABLE_INSTITUTION',
    ENABLE_INSTITUTION = 'ENABLE_INSTITUTION',
    UPDATE_DASHBOARD = 'UPDATE_DASHBOARD',
    DELETE_DASHBOARD = 'DELETE_DASHBOARD',
    CREATE_DASHBOARD = 'CREATE_DASHBOARD',
    VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    DISABLE_DASHBOARD = 'DISABLE_DASHBOARD',
    ENABLE_DASHBOARD = 'ENABLE_DASHBOARD',


    
    CREATE_DASHBOARD_TYPE = 'CREATE_DASHBOARD_TYPE',
    DELETE_DASHBOARD_TYPE = 'DELETE_DASHBOARD_TYPE',
    VIEW_DASHBOARD_TYPE = 'VIEW_DASHBOARD_TYPE',




    CREATE_DASHBOARD_CATEGORY = 'CREATE_DASHBOARD_CATEGORY',
    UPDATE_DASHBOARD_CATEGORY = 'UPDATE_DASHBOARD_CATEGORY',
    VIEW_DASHBOARD_CATEGORY = 'VIEW_DASHBOARD_CATEGORY',




    CREATE_REPORT = 'CREATE_REPORT',
    VIEW_REPORT = 'VIEW_REPORT',
    DOWNLOAD_REPORT = 'DOWNLOAD_REPORT',




    CREATE_REPORT_TYPE = 'CREATE_REPORT_TYPE',
    UPDATE_REPORT_TYPE = 'UPDATE_REPORT_TYPE',
    ENABLE_REPORT_TYPE = 'ENABLE_REPORT_TYPE',
    DISABLE_REPORT_TYPE = 'DISABLE_REPORT_TYPE',
    VIEW_REPORT_TYPE = 'VIEW_REPORT_TYPE',




    CREATE_ROLE = 'CREATE_ROLE',
    DELETE_ROLE = 'DELETE_ROLE',
    UPDATE_ROLE = 'UPDATE_ROLE',
    ENABLE_ROLE = 'ENABLE_ROLE',
    DISABLE_ROLE = 'DISABLE_ROLE',
    VIEW_ROLE = 'VIEW_ROLE',



    VIEW_PERMISSION = 'VIEW_PERMISSION',



    UPDATE_TRANSLATION = 'UPDATE_TRANSLATION',
    VIEW_TRANSLATION = 'VIEW_TRANSLATION',
}
